### PR TITLE
Use ninja generator for build

### PR DESCRIPTION
**Pull request by apram0d**
With default build generator we are seeing error:
 c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
This is observed even running with single thread. This is not seen when using ninja generator.

### CODE REVIEW

**Comment by jwludzik** [comment]
@apram0d , what version of system, cmake and gcc do you use? Is the default build generator on your side is Unix Makefile?

**Comment by apram0d** [comment]
@jwludzik I am using Ubuntu 22.04, cmake version 3.18.4 and  gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

yes default build generator is Unix MakeFile

**Comment by jwludzik** [comment]
Thanks for feedback! I suspect that vpux_compiler_build.cmake has wrong parameters, I will try to investigate it

There is one more solution to fix compilation issue, it requires to increase the swap memory

**Comment by apram0d** [comment]
Even increasing the swap memory to +4GiB , the issue still persists.

**Comment by jwludzik** [comment]
Thanks! You can try to reduce the number of processes in https://github.com/intel/linux-vpu-driver/blob/main/compiler/vpux_compiler_build.cmake#L18 

ex.
```
math(EXPR PARALLEL_PROCESSES ${PARALLEL_PROCESSES}/4)
```

**Pull request closed without merging**
